# Generated by Django 3.0.6 on 2020-05-07 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('tech_used', models.CharField(max_length=200)),
                ('criterion', models.CharField(default='None', max_length=200)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('enrollment_id', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=200)),
                ('department', models.CharField(max_length=60)),
                ('cgpa', models.CharField(max_length=10)),
                ('statement_of_purpose', models.CharField(max_length=1000)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
