# Generated by Django 3.0.6 on 2020-05-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
