# Generated by Django 3.0.6 on 2020-05-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_application_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
