# Generated by Django 3.0.6 on 2020-06-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_application_is_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(default='default.pdf', upload_to='resume'),
        ),
    ]
