# Generated by Django 3.0.6 on 2020-07-06 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_application_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='application',
            name='department',
        ),
        migrations.RemoveField(
            model_name='application',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='application',
            name='enrollment_id',
        ),
        migrations.RemoveField(
            model_name='application',
            name='name',
        ),
    ]
