# Generated by Django 3.0.6 on 2020-07-10 13:28

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('projects', '0006_auto_20200706_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tech_used',
        ),
        migrations.AddField(
            model_name='project',
            name='tech_used',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
