# Generated by Django 3.0.6 on 2020-07-16 07:39

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('projects', '0007_auto_20200710_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicationstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Projectstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_used',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
