# Generated by Django 3.0.6 on 2020-07-16 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200716_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='is_selected',
        ),
        migrations.AddField(
            model_name='application',
            name='application_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.Applicationstatus'),
        ),
    ]
