# Generated by Django 3.0.6 on 2020-07-16 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200716_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_open',
        ),
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.Projectstatus'),
        ),
    ]
