# Generated by Django 3.0.6 on 2020-07-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.AddField(
            model_name='student',
            name='cgpa',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_id',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
